name: gringotts
description: Mobile first Plain Text Accounting
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  antlr4: ^4.11.1
  decimal: ^2.2.0
  fast_immutable_collections: ^7.4.1
  http: ^0.13.4
  ninja: ^3.0.7
  rsa_pkcs: ^2.0.1

dev_dependencies:
  import_sorter: ^4.6.0
  test: ^1.19.5
