name: gringotts
description: Plain Text Accounting for Mobiles
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  petitparser: ^2.4.0
  decimal: ^0.3.3

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
