name: beany_core
description: Mobile first Plain Text Accounting
version: 0.0.1

environment:
  sdk: ">=3.0.0"

dependencies:
  antlr4: ^4.12.0
  decimal: ^2.3.2
  fast_immutable_collections: ^9.0.0
  http: ^0.13.4
  ninja: ^3.0.7
  rsa_pkcs: ^2.0.1
  equatable: ^2.0.5
  quiver: ^3.2.1
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.19.5
