name: beany
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.13.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_date_range_picker: ^0.0.14
  beany_backend:
    path: ../backend
  beany_core:
    path: ../core
  google_fonts: ^4.0.4
  fl_chart: ^0.66.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
