name: beany_importer
description: Wise integration for Beany
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.1.4

dependencies:
  yaml: ^3.1.2
  beany_core:
    path: ../core
  path: ^1.8.3
  fast_immutable_collections: ^9.1.6
  collection: ^1.18.0
  csv: ^6.0.0
  intl: ^0.19.0
  decimal: ^2.3.3
  meta: ^1.14.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
