name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.13.6
        cache: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: antlr4
        version: 1.0
    - uses: bluefireteam/melos-action@v1
      name: Bootstrap
    - name: Generate Code
      run: cd core && make parser
    - name: Tests
      run: cd core && make test