name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Dependencies
    - name: Get Flutter version from pubspec
      run: |
        set -e
        FLUTTER_VERSION=$(cat app/pubspec.yaml | grep 'flutter:' | head -n 1 | awk '{ print $2 }' | tr -d '"' | cut -d "=" -f 2)
        echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> $GITHUB_ENV
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.13.6
        cache: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
      name: Antlr4 Dependencies
      with:
        packages: default-jre-headless wget
    - name: Download Antlr4
      run: |
        export ANTLR_VERSION=4.13.1
        wget https://www.antlr.org/download/antlr-${ANTLR_VERSION}-complete.jar -O /tmp/antlr-${ANTLR_VERSION}-complete.jar
        echo "java -jar /tmp/antlr-${ANTLR_VERSION}-complete.jar \"\$@\"" >> /usr/bin/antlr
        sudo chmod +x /usr/bin/antlr

    - uses: bluefireteam/melos-action@v1
      name: Bootstrap
    - name: Generate Code
      run: cd core && make parser && make build
    - name: Tests
      run: cd core && make test